<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA1B9LLY\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA1B9LLY/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerA1B9LLY.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerA1B9LLY\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerA1B9LLY\appAppKernelProdContainer([
    'container.build_hash' => 'A1B9LLY',
    'container.build_id' => '74dce5d5',
    'container.build_time' => 1678884279,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA1B9LLY');
