<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXosWeuB\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXosWeuB/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerXosWeuB.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerXosWeuB\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerXosWeuB\appAppKernelProdContainer([
    'container.build_hash' => 'XosWeuB',
    'container.build_id' => 'a4c64d90',
    'container.build_time' => 1677069563,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXosWeuB');
